[phases.setup]
nixPkgs = ["...", "gcc", "binutils", "python311", "python311Packages.pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn server:app --bind 0.0.0.0:$PORT"