[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "gcc", "gcc-unwrapped", "glibc", "glibc.dev"]

[phases.install]
cmds = [
    "pip install --upgrade pip",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn server:app --bind 0.0.0.0:$PORT"

[build]
cacheDirectories = ["/root/.cache/pip"]